### ISSUE TITLE
Link to STSW-STM32138

### ISSUE THREAD

**Issue by atsju** [STMicroelectronics/stm32f429i-discovery#1]
Looking at release notes it seems that this repo is based on [STSW-STM32138](https://www.st.com/en/embedded-software/stsw-stm32138.html)
One release note is missing V1.0.3 and I'm afraid that 2 "identical" package will evolve in parallel.
Please check internally and maybe the STSW-STM32138 should now link to this github repository for most up to date versions.

**Comment by bmcdonnell-fb** [comment]
I don't recall how this repo relates to others, but at the bottom of the description of https://github.com/STMicroelectronics/STM32CubeF4/issues/80, I noted the divergence between [STSW-STM32138](https://www.st.com/en/embedded-software/stsw-stm32138.html) and [STM32CubeF4](https://github.com/STMicroelectronics/STM32CubeF4/).

**Comment by ALABSTM** [comment]
Hi @atsju,

Thank you for your report. Actually, the link you indicated deals with a package part of our **SPL** (Standard Peripheral Library). This one is part of our more recent **Cube** HAL library. Hence, the two packages are not "identical".

Thank you again for your interest. Please allow me to close this issue.

With regards,
